language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  pip install codecov

install:
  "pip install -r requirements.txt"

script:
    - python setup.py install
    - coverage run -m py.test tests
    - bash <(curl -s https://codecov.io/bash)
